#!/bin/sh

case "$1" in
    remove|abort-install|disappear)
    # Remove divert
    FLE=/usr/bin/apt
    if [ -f $FLE ]; then
      dpkg-divert --remove --rename $FLE
    fi
    
    # Remove any symlings to the SolydXK logos
    find /usr/share/icons -type l -iname "*solyd*" ! -path "*evolvere-additional*" -exec rm {} \;
    ;;
esac
